import Head from 'next/head'
import { useState } from 'react'
import { Inter } from '@next/font/google'
import connectionDB from '../utils/mongodb'
import User from '../models/user'
import Publication from '../models/publication'
import IUser from '../types/user'
import { IPublication } from '../types/publication'
import SearchBar from '../components/SearchBar'
import PublicationBar from '../components/PublicationBar'
import Publications from '../components/Publications'
import { Grid } from '@mui/material'

const inter = Inter({ subsets: ['latin'] })

interface Props {
  allUsers: IUser[],
  allPublications: IPublication[]
}

export default function Home({ allUsers, allPublications }: Props) {
  const [publications, setPublications] = useState<IPublication[]>(allPublications)

  return (
    <>
      <Head>
        <title>Photoland</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid
        container
        direction='column'
        alignItems='center'
        gap={2}
      >
        <SearchBar allUsers={allUsers} />
        <PublicationBar publications={publications} setPublications={setPublications} />
        <Publications publications={publications} />
      </Grid>
    </>
  )
}

export async function getServerSideProps() {
  connectionDB()
  const allUsers = await User.find({}).lean()
  const allPublications = await Publication.find({}).populate('user').lean()

  return {
    props: {
      allUsers: JSON.parse(JSON.stringify(allUsers)),
      allPublications: JSON.parse(JSON.stringify(allPublications.reverse()))
    }
  }
}